name: build-and-release

on:
  push:
    tags:
      - v*

env:
  TAG_NAME: ${{ github.ref }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: gcc puissance.c -o puissance-linux.bin
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: puissance-linux
          path: ./puissance-linux.bin

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: gcc puissance.c -o puissance-macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: puissance-macos
          path: ./puissance-macos

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: gcc puissance.c -o puissance-windows.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: puissance-windows
          path: ./puissance-windows.exe

  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: puissance-linux
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: puissance-macos
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: puissance-windows
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            Changes in this release:
            * Fix some bugs
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./puissance-linux.bin
          asset_name: puissance-linux.bin
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./puissance-macos
          asset_name: puissance-macos
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
