name: build-and-release

on:
  push:
    tags:
      - v*

env:
  TAG_NAME: ${{ github.ref }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: gcc puissance.c -o puissance-linux.bin
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: puissance-linux
          path: ./puissance-linux.bin

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: gcc puissance.c -o puissance-macos
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: puissance-macos
          path: ./puissance-macos

#  build-windows:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Build
#        run: gcc puissance.c -o puissance-windows.exe
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: puissance-windows
#          path: ./puissance-windows.exe

  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: puissance-linux
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: puissance-macos
#      - name: Download artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: release3
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            puissance-linux.bin
            puissance-macos
#            puissance-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
